"""audit tables

Revision ID: 0d79cf5f218b
Revises: f947cb65c1ef
Create Date: 2025-07-23 07:20:11.832603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d79cf5f218b'
down_revision: Union[str, Sequence[str], None] = 'f947cb65c1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.Column('best_practices_score', sa.Float(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('pwa_score', sa.Float(), nullable=True),
    sa.Column('full_report', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_results_id'), 'audit_results', ['id'], unique=False)
    op.create_index(op.f('ix_audit_results_page_url'), 'audit_results', ['page_url'], unique=False)
    op.create_index(op.f('ix_audit_results_website_id'), 'audit_results', ['website_id'], unique=False)
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_crawled', sa.DateTime(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('IsArchived', sa.Boolean(), nullable=True),
    sa.Column('ArchivedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ArchivedBy', sa.String(length=100), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_url'), 'websites', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websites_url'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_audit_results_website_id'), table_name='audit_results')
    op.drop_index(op.f('ix_audit_results_page_url'), table_name='audit_results')
    op.drop_index(op.f('ix_audit_results_id'), table_name='audit_results')
    op.drop_table('audit_results')
    # ### end Alembic commands ###
