"""Initial migration

Revision ID: 3b4a922bac87
Revises: 
Create Date: 2025-07-23 01:55:43.913067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4a922bac87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('UserId', sa.UUID(), nullable=False),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('HashedPassword', sa.String(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('IsArchived', sa.Boolean(), nullable=True),
    sa.Column('ArchivedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ArchivedBy', sa.String(length=100), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_index('idx_email_active', 'User', ['Email', 'IsActive'], unique=False)
    op.create_index(op.f('ix_User_Email'), 'User', ['Email'], unique=True)
    op.create_index(op.f('ix_User_UserId'), 'User', ['UserId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_UserId'), table_name='User')
    op.drop_index(op.f('ix_User_Email'), table_name='User')
    op.drop_index('idx_email_active', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
